### ISSUE TITLE
Crash after doze

### ISSUE THREAD

**Issue by Rexios80** [Rexios80/SR-Tracker-for-Overwatch#6]
Process: com.rexios.overwatchsrt, PID: 15700
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rexios.overwatchsrt/com.rexios.overwatchsrt.InformationActivity}: java.lang.IllegalStateException: Invalid tables
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                    Caused by: java.lang.IllegalStateException: Invalid tables
                                                       at android.database.sqlite.SQLiteDatabase.findEditTable(SQLiteDatabase.java:975)
                                                       at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1166)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                       at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                                                       at com.rexios.overwatchsrt.DatabaseParser.<init>(DatabaseParser.java:91)
                                                       at com.rexios.overwatchsrt.InformationActivity.onCreate(InformationActivity.java:38)
                                                       at android.app.Activity.performCreate(Activity.java:6682)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                       at java.lang.reflect.Method.invoke(Native Method)

**Comment by Rexios80** [comment]
Move if (savedInstanceState != null) above DatabaseParser declaration in InformationActivity.
