### ISSUE TITLE
Time Analysis Fragment crashes after doze

### ISSUE THREAD

**Issue by Rexios80** [Rexios80/SR-Tracker-for-Overwatch#7]
ProGuard obfuscation makes it hard to find the root cause of the issue, but this is the stack trace:
FATAL EXCEPTION: main
                                                   Process: com.rexios.overwatchsrt, PID: 28033
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.rexios.overwatchsrt/com.rexios.overwatchsrt.TimeAnalysisActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class fragment
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                    Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class fragment
                                                    Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class fragment
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList com.rexios.overwatchsrt.c.i()' on a null object reference
                                                       at com.rexios.overwatchsrt.TimeAnalysisFragment.onCreateView(Unknown Source)
                                                       at android.support.v4.app.Fragment.isSupportFragmentClass(Unknown Source)
                                                                                          getContext
                                                                                          setMenuVisibility
                                                                                          getLayoutInflater
                                                                                          onOptionsMenuClosed
                                                                                          onContextItemSelected
                                                                                          performCreateView
                                                                                          performCreateOptionsMenu
                                                                                          setStateAfterAnimating
                                                                                          access$800
                                                       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
                                                                                                     shouldRunOnHWLayer
                                                                                                     throwException
                                                                                                     beginTransaction
                                                                                                     popBackStackImmediate
                                                                                                     putFragment
                                                                                                     getFragment
                                                                                                     saveFragmentInstanceState
                                                                                                     dump
                                                                                                     makeOpenCloseAnimation
                                                                                                     makeFadeAnimation
                                                                                                     loadAnimation
                                                                                                     moveToState
                                                                                                     moveToState
                                                                                                     addFragment
                                                                                                     findFragmentById
                                                                                                     findFragmentByTag
                                                                                                     setBackStackIndex
                                                                                                     execSingleAction
                                                                                                     executePostponedTransaction
                                                                                                     executeOpsTogether
                                                                                                     makeRemovedFragmentsInvisible
                                                                                                     postponePostponableTransactions
                                                                                                     completeExecute
                                                                                                     addBackStackState
                                                                                                     popBackStackState
                                                                                                     restoreAllState
                                                                                                     attachController
                                                                                                     dispatchMultiWindowModeChanged
                                                                                                     dispatchConfigurationChanged
                                                                                                     dispatchCreateOptionsMenu
                                                                                                     dispatchPrepareOptionsMenu
                                                                                                     dispatchOptionsItemSelected
                                                                                                     dispatchOnFragmentPreAttached
                                                                                                     dispatchOnFragmentCreated
                                                                                                     dispatchOnFragmentViewCreated
                                                                                                     onCreateView
                                                                                                     access$200
                                                                                                     access$300
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                                                                                     startPendingDeferredFragments
                                                                                                     freeBackStackIndex
                                                                                                     ensureExecReady
                                                                                                     generateOpsForPendingActions
                                                                                                     dispatchOnFragmentResumed
                                                                                                     dispatchOnFragmentSaveInstanceState
                                                       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
                                                                                                     shouldRunOnHWLayer
                                                                                                     throwException
                                                                                                     beginTransaction
                                                                                                     popBackStackImmediate
                                                                                                     putFragment
                                                                                                     getFragment
                                                                                                     saveFragmentInstanceState
                                                                                                     dump
                                                                                                     makeOpenCloseAnimation
                                                                                                     makeFadeAnimation
                                                                                                     loadAnimation
                                                                                                     moveToState
                                                                                                     moveToState
                                                                                                     addFragment
                                                                                                     findFragmentById
                                                                                                     findFragmentByTag
                                                                                                     setBackStackIndex
                                                                                                     execSingleAction
                                                                                                     executePostponedTransaction
                                                                                                     executeOpsTogether
                                                                                                     makeRemovedFragmentsInvisible
                                                                                                     postponePostponableTransactions
                                                                                                     completeExecute
                                                                                                     addBackStackState
                                                                                                     popBackStackState
                                                                                                     restoreAllState
                                                                                                     attachController
                                                                                                     dispatchMultiWindowModeChanged
                                                                                                     dispatchConfigurationChanged
                                                                                                     dispatchCreateOptionsMenu
                                                                                                     dispatchPrepareOptionsMenu
                                                                                                     dispatchOptionsItemSelected
                                                                                                     dispatchOnFragmentPreAttached
                                                                                                     dispatchOnFragmentCreated
                                                                                                     dispatchOnFragmentViewCreated
                                                                                                     onCreateView
                                                                                                     access$200
                                                                                                     access$300
                                                       at android.support.v4.app.FragmentController.createController(Unknown Source)
                                                                                                    getSupportFragmentManager
                                                                                                    findFragmentByWho
                                                                                                    attachHost
                                                                                                    onCreateView
                                                                                                    restoreAllState
                                                                                                    dispatchMultiWindowModeChanged
                                                                                                    dispatchConfigurationChanged
                                                                                                    dispatchCreateOptionsMenu
                                                                                                    dispatchPrepareOptionsMenu
                                                                                                    dispatchOptionsItemSelected
                                                                                                    restoreLoaderNonConfig
                                                                                                    dumpLoaders
                                                       at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(Unknown Source)
                                                                                                  onPrepareOptionsPanel
                                                                                                  viewToString
                                                                                                  dumpViewHierarchy
                                                                                                  doReallyStop
                                                                                                  onAttachFragment
                                                                                                  startActivityFromFragment
                                                       at android.support.v4.app.BaseFragmentActivityHoneycomb.onCreateView(Unknown Source)
                                                       at android.support.v4.app.FragmentActivity.onCreateView(Unknown Source)
                                                                                                  onCreateView
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:777)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                       at android.support.v7.app.AppCompatDelegateImplV9.onPostCreate(Unknown Source)
                                                                                                         setContentView
                                                                                                         addContentView
                                                                                                         onTitleChanged
                                                                                                         onMenuOpened
                                                                                                         startSupportActionMode
                                                                                                         onKeyUp
                                                                                                         callActivityOnCreateView
                                                                                                         initializePanelMenu
                                                                                                         preparePanel
                                                                                                         checkCloseActionMenu
                                                       at android.support.v7.app.AppCompatActivity.setContentView(Unknown Source)
                                                                                                   setContentView
                                                                                                   setContentView
                                                       at com.rexios.overwatchsrt.TimeAnalysisActivity.onCreate(Unknown Source)
                                                       at android.app.Activity.performCreate(Activity.java:6682)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by Rexios80** [comment]
I figured out that ending the apps cached process allows me to reproduce the error. It's because I was accessing the DatabaseParser from the InformationActivity without recreating it.
